
// Полный список транспортных средств
const VEHICLES = [
	// ЛЕГКОВЫЕ
    'ЗАЗ-968 "Запорожец"',
	"ВАЗ-1111 Ока",
	"Ваз-2101",
	"Москвич-2140",
	"Москвич 2141S",
	"ВАЗ-2106",
	"ВАЗ-2104",
	"ИЖ 21251 Комби",
	"ГАЗ-24 Волга",
	"ВАЗ-2108",
	"ВАЗ-2107",
	"ВАЗ-2109",
	"Daewoo Matiz",
	"ВАЗ-2108 Рестайлинг",
	"ВАЗ-21099",
	"ВАЗ-2110",
	"Volkswagen Passat GL (B3)",
	"ВАЗ-2109 Рестайлинг",
	"ВАЗ-21124",
	"ГАЗ-3110 Волга",
	"ВАЗ-2113",
	"ВАЗ-2114",
	"ВАЗ-2115",
	"ГАЗ-3102",
	"Mercedes-Benz 190E (W201)",
	"Mercedes-Benz 250D (W124)",
	"Lada Priora",
	"Peugeot 406",
	"Chevrolet Lacetti",
	"УАЗ-469",
	"Renault Megane",
	"Lada Granta",
	"Renault Logan",
	"Audi 80 Avant (B4)",
	"Chevrolet Caprice Classic",
	"Peugeot 207",
	"Skoda Superb",
	"Lada Largus",
	"Mazda 3",
	"Toyota Mark II Tourer V (90JZX)",
	"Chevrolet Niva",
	"Lada 4x4 Urban",
	"УАЗ Хантер",
	"Chevrolet Cruze",
	"УАЗ Патриот",
	"Toyota Mark II Tourer V (100JZX)",
	"BMW 535i (E34)",
	"Volkswagen Golf IV",
	"Nissan Leaf",
	"Nissan Skyline GTS-T Type-M (R-32)",
	"УАЗ-2206 Буханка",
	"Volkswagen Golf 2.0 TSI (VI)",
	"Toyota Chaser Tourer V (JZX100) Дорестайлинг",
	"Toyota Chaser Tourer V (JZX100)",
	"УАЗ-3909",
	"Nissan Stagea",
	"Nissan 200SX",
	"Honda Accord",
	"Mazda RX-8",
	"BMW 530d (E39)",
	"Mercedes-Benz E240 (W210)",
	"Ford Focus 3",
	"Toyota Supra (A80)",
	"Lada Vesta",
	"Volkswagen Polo",
	"KIA Rio",
	"Subaru Forester XT",
	"Toyota Altezza RS200",
	"Nissan Skyline GT-R V-spec (R34)",
	"Skoda Rapid 2020",
	"Chevrolet Suburban",
	"Subaru Forester (SG9)",
	"Jeep Grand Cherokee (ZJ)",
	"Volvo 850 R",
	"Mazda RX-7 (FD)",
	"BMW 750i (E38)",
	"Mitsubishi Lancer Evolution IX MR",
	"Mercedes-Benz 600SEL (W140)",
	"Subaru Impreza WRX STI",
	"Nissan 350Z",
	"Skoda Octavia",
	"KIA Optima SXL",
	"Subaru BRZ",
	"Mitsubishi Lancer Evolution X",
	"Land Rover Range Rover",
	"BMW X5 (E53)",
	"Lada Vesta Sport",
	"Mercedes-Benz S600 (W220)",
	"Audi A3 sedan",
	"Mercedes-Benz 560SEL (W126)",
	"BMW 530d Touring (F11)",
	"GMC Vandura",
	"Audi S4 (B8)",
	"Chevrolet Tahoe LTZ",
	"Volkswagen Jetta",
	"Lexus IS 350 F",
	"Mercedes-Benz ML 63 AMG (W164)",
	"Audi A4 Allroad quattro",
	"KIA Stinger GT",
	"Volkswagen Touareg V8 TDI",
	"BMW M5 (E60)",
	"Audi Q7 V12 TDI",
	"BMW M3 (e46)",
	"Subaru WRX STI (VA)",
	"Mercedes-Benz C63 AMG (w204)",
	"BMW M3 (e92)",
	"Toyota Land Cruiser Prado",
	"Volvo V60 Polestar",
	"BMW Z4",
	"Jeep Wrangler Rubicon",
	"Toyota Camry 3.5 (XV70)",
	"Audi Q7 TDI",
	"BMW M4 (F82)",
	"Maseratti GranTurismo",
	"Mercedes-Benz CLS63 AMG (C218) Дорест",
	"Volvo XC90 T5",
	"Mercedes-Benz E63 S AMG (w212)",
	"Ford Mustang Shelby GT500",
	"BMW M6 (F13)",
	"Mercedes-Benz CLS63 AMG (C218) Рестайлинг",
	"Jaguar F-Type R",
	"Volkswagen Multivan T6.1",
	"Mercedes-Benz C63 S Coupe AMG (w205)",
	"Mercedes-Benz C200 (W206)",
	"Toyota Land Cruiser 200 Executive Lounge",
	"Cadillac Escalade ESV",
	"Toyota Supra (A90)",
	"BMW X5 M (F85)",
	"Ford Mustang GT 2015",
	"Mercedes-Benz V300d",
	"Dodge Challenger SRT Hellcat",
	"Hummer H2",
	"Chevrolet Camaro ZL1",
	"Audi A8 (D4)",
	"Nissan 400Z",
	"Audi RS6 Avant (C7)",
	"Toyota Tundra",
	"Chevrolet Corvette ZR1",
	"Range Rover Sport SVR",
	"Infiniti QX80",
	"Li L9",
	"Audi S8 Plus (D4)",
	"BMW X6 M (F86)",
	"Toyota Land Cruiser 300",
	"Lexus LX570",
	"BMW M4 (G82)",
	"BMW M5 (F90)",
	"Nissan GT-R (R35)",
	"Jeep Grand Cherokee Trackhawk",
	"BMW M760 Li xDrive (G12)",
	"Mercedes-Benz E63 S AMG (w213)",
	"Porsche 911 Carrera S (992)",
	"Mercedes-Benz GLS63 AMG",
	"Mercedes-Maybach S650 (X222)",
	"Audi RS6 Avant (C8)",
	"Audi RS7 (C8)",
	"Mercedes-Benz G65 AMG (W463)",
	"Audi SQ8",
	"Porsche Cayenne Turbo",
	"Porsche Panamera Turbo",
	"Mercedes-Benz G500 (W464)",
	"Mercedes-Benz E63 S (W213) рестайлинг",
	"Range Rover SVAutobiography",
	"BMW M5 (F90) LCI",
	"Porsche Taycan Turbo S",
	"BMW X7",
	"Porsche Panamera Turbo S Sport Turismo",
	"Mercedes-AMG GT 63 S 4MATIC+",
	"Mercedes-Benz GLE Coupe 450d",
	"Audi R8",
	"Tesla Model X Plaid",
	"Acura NSX",
	"Bentley Continental GT",
	"BMW X6 M (F96)",
	"Mercedes-AMG GT R",
	"RAM TRX",
	"BMW X5 M (F95)",
	"Range Rover (L460)",
	"Tesla Model S Plaid",
	"BMW M8 Competition",
	"Ferrari 488 GTB",
	"Bentley Bentayga W12",
	"Mercedes-Benz G63 AMG (W464)",
	"Lamborghini Huracan EVO",
	"Porsche 911 GT3 (992)",
	"Lamborghini Urus",
	"Porsche 911 Turbo S (992)",
	"Rolls-Royce Wraith",
	"Ferrari Portofino",
	"McLaren 720S Spyder",
	"Lamborghini Aventador S Roadster",
	"Rolls-Royce Phantom VIII",
	"Ferrari Purosangue",
	"Rolls-Royce Cullinan",
	"Lexus LFA",
	"Ferrari LaFerrari",
	"Bugatti Chiron Sport",
	"Bugatti Chiron Super Sport",
	"ГАЗ-3309 Дорест",
	"ГАЗ-3309 Рест",
	"ГАЗ-3302 Тент",
	"ГАЗ-3302 Будка",
	"ГАЗ-66",
	"GMC Vandura",
	"ГАЗель NEXT",
	"ЗИЛ 131 Тент",
	"ГАЗель NEXT",
	"КамАЗ 53212 Тент",
	"КамАЗ 53212 Контейнер",
	"Mercedes-Benz Sprinter Classic 311 CDI",
	"KAMAZ-5490 NEO",
	"Renault Magnum",
	"Scania Topline R480",
	"Volvo VNL",
	"Scania R500",
	"Mercedes-Benz Actros",
	"Volvo FH",
	"Lamborghini Huracan Sterrato",
	"ГАЗель БИЗНЕС",
	"КАвЗ-3270",
	"ПАЗ-32053 (бензин)",
	"ПАЗ-32054 (бензин)",
	"ПАЗ-32054 (дизель)",
	"Богдан А092",
	"ГАЗель NEXT A64R42 Ситилайн",
	"ПАЗ-4234 (дизель)",
	"Богдан А09302",
	"Богдан А09304 Атаман",
	"КАвЗ-685М",
	"ПАЗ-32053 рестайлинг (бензин)",
	"ПАЗ-32054 рестайлинг (бензин)",
	"Mercedes-Benz Sprinter Classic 411 CDI (Base)",
	"Mercedes-Benz Sprinter Classic 411 CDI (AS3)",
	"ПАЗ-320405-04 Вектор Next",
	"ГАЗель NEXT",
	"ПАЗ 672М",
	"ПАЗ-320414-05 Вектор",
	"ПАЗ-4230 Аврора",
	"ЛАЗ-695Н",
	"ЛиАЗ-5256.00 (поздний вариант)",
	"ЛАЗ-4207",
	"ЛиАЗ 5256.00-11",
	"КАвЗ-4238 Аврора",
	"ЛАЗ-5207",
	"ЛиАЗ 5256.40",
	"Ikarus 260 (ширмовые двери)",
	"Ikarus 260 (платетарные двери)",
	"Scania OmniLink CK95UB 4x2 LB (2 doors)",
	"Scania OmniLink CK95UB 4x2 LB (3 doors)",
	"ЛиАЗ 4292",
	"ЛАЗ-697Р Турист",
	"Ikarus 256.54",
	"ЛиАЗ-5256.00",
	"ЛиАЗ-5292.22",
	"МАЗ-203",
	"Ikarus 250.59",
	"ЛАЗ-699Р Турист",
	"ЛиАз-677М",
	"ЛиАз-677 (ранний)",
	"ЛиАз-677Э (экспортный)",
	"Honda Dio AF 35 ZX",
	"ИЖ Юпитер-5",
	"Honda Gold Wing GL1500",
	"Yamaha XT660",
	"Yamaha XVS400 Drag Star",
	"Yamaha XVS400 Drag Star Classic",
	"Yamaha WR250F",
	"Honda CBR1100XX Super Blackbird",
	"KTM 690 Enduro R",
	"Harley-Davidson Fat Boy Lo",
	"Ducati Diavel Carbon",
	"Suzuki GSX 1300 R Hayabusa",
	"Harley-Davidson Sportster S",
	"Kawasaki Vulcan VN900 Classic",
	"Indian Chief Dark Horse",
	"BMW S1000RR",
	"Nissan Silvia S15 Spec-R",
	"Honda Civic Type-R",
	'ГАЗ-М20 "Победа"',
	"ЗИЛ 133540",
	"BMW 850 CSi",
	"КамАЗ 54115",
	"Honda NSX",
	"Alfa Romeo Giulia",
	"Cadillac CTS-V",
	"Ferrari 348 GTB",
	"Ferrari 348 GTS",
	'ГАЗ-13 "Чайка"',
	"Chevrolet El Camino SS",
	"Dodge Charger R/T 1969",
	"Ford F-150 Shelby 2020",
	"Dodge Challenger SRT Demon",
	"Dodge Charger SRT Hellcat",
	"Ford F-450",
	"Porsche 911 Carrera 993",
	'ГАЗ 3102 "Защитник"',
	'Chevrolet Caprice Classic "Purple Rose"',
	'УАЗ Хантер "Победа"',
	'Honda Civic Type-R "Underground"',
	"BMW M4 (G82) CSL",
	'Mitsubishi Lancer Evolution X "Фантом"',
	'ПАЗ-672М "Дедморобус"',
	'BMW M6 (F13) HAMANN "Mirror"',
	'ГАЗ-13 "Чайка" 9 Мая',
	"Audi RS6-R (C8) ABT",
	'Ferrari 488 GTB "Liberty Walk"',
	'Porsche 911 Turbo S "Тыквоголовая"',
	"BMW M3 (E46) Most Wanted",
	"BMW M3 (E46) Most Wanted Edition",
	'Ford Mustang Shelby GT500 "Eleanor"',
	'ВАЗ-21011 "Сгущёнка"',
	'ВАЗ-21011 "Сода"',
	'Chevrolet Camaro ZL1 "Spooky"',
	'BMW M8 Competition "Radio Legend"',
	"BMW M5 (E60) HAMANN",
	'ВАЗ-1111 "Ока" FOOLS DAY',
	'ГАЗ-24 "Космос"',
	'ВАЗ-2108 "Буран"',
	'ВАЗ-2108 "Birthday Race"',
	'ВАЗ-2107 VFTS "Autumn Drift"',
	'ВАЗ-2107 "Joke"',
	"Mercedes-Benz 190E (W201) AMG 3.2 \"Barolorot\"",
	"Mercedes-Benz 190E (W201) AMG 3.2 \"Blauschwartz\"",
	"Mercedes-Benz 190E (W201) AMG 3.2 \"Classic Weiss\"",
	"УАЗ-3909 \"Оборона\"",
	"Nissan Silvia S15 Spec-R \"Akima\"",
	"Subaru Impreza WRX STI \"Снежинка\"",
	"GMC Vandura \"The Mystery Machine\"",
	"ПАЗ Vector Next \"Radio Province\"",
	"Mercedes-Benz C63 AMG (W204) \"Камуфляж\"",
	"Mercedes-Benz C63 AMG (W204) \"Сакура\"",
	"Jeep Wrangler Rubicon \"Кровавый\"",
	"Indian Chief Dark Horse \"Fire Chopper\"",
	"Indian Chief Dark Horse \"The Lone Wolf\"",
	"Indian Chief Dark Horse \"Vintage\"",
	"ЛАЗ-695Н \"Дедморобус\"",
	"Toyota Supra (A90) Targa",
	"Nissan 400Z Pandem \"Senshi\"",
	"Chevrolet El Camino SS \"Dia de los Muertos\"",
	"Ford F-150 Shelby \"Silver Skull\"",
	"Nissan GT-R (R35) \"Radio Province\"",
	"Dodge Charger SRT Hellcat \"10th Anniversary\"",
	"Dodge Charger SRT Hellcat \"Demon's Spring\"",
	"ЛиАЗ-677М \"Дедморобус\"",
	"Porsche 911 Carrera (993) RWB \"Slimmer\"",
	"RAM TRX Icebreaker",
	"Tesla Model S \"Radio Province\"",
	"Porsche 911 Turbo S (992) \"Cyberpunk\""
].sort();

// Функция для создания выпадающего списка с поиском
function createVehicleSearchableSelect(inputId) {
    const input = document.getElementById(inputId);
    if (!input) return null;
    
    input.classList.add('vehicle-search-input');
    input.setAttribute('autocomplete', 'off');
    
    const container = document.createElement('div');
    container.className = 'vehicle-search-container';
    container.style.position = 'relative';
    container.style.width = '100%';
    
    input.parentNode.insertBefore(container, input);
    container.appendChild(input);
    
    const dropdown = document.createElement('div');
    dropdown.className = 'vehicle-dropdown';
    dropdown.id = `${inputId}-dropdown`;
    dropdown.style.display = 'none';
    container.appendChild(dropdown);
    
    function showDropdown() {
        const filter = input.value.toLowerCase();
        const filteredVehicles = VEHICLES.filter(v => v.toLowerCase().includes(filter));
        
        if (filteredVehicles.length === 0) {
            dropdown.innerHTML = '<div style="padding: 8px 12px; color: #6b7f99;">Нет совпадений</div>';
        } else {
            dropdown.innerHTML = filteredVehicles.map(v => 
                `<div class="vehicle-option" style="padding: 8px 12px; cursor: pointer; border-bottom: 1px solid #eee;">${v}</div>`
            ).join('');
            
            dropdown.querySelectorAll('.vehicle-option').forEach(option => {
                option.addEventListener('click', function(e) {
                    e.preventDefault();
                    // ИСПРАВЛЕНИЕ: берем textContent вместо data-value
                    input.value = this.textContent;
                    dropdown.style.display = 'none';
                    input.focus();
                    input.dispatchEvent(new Event('input', { bubbles: true }));
                });
            });
        }
        
        dropdown.style.display = 'block';
    }
    
    // Остальной код без изменений...
    input.addEventListener('focus', showDropdown);
    input.addEventListener('input', showDropdown);
    
    input.addEventListener('blur', function() {
        setTimeout(() => {
            dropdown.style.display = 'none';
        }, 200);
    });
    
    return input;
}

// Инициализация всех полей с классом 'vehicle-searchable'
function initVehicleSearchableFields() {
    console.log('Initializing vehicle searchable fields...');
    document.querySelectorAll('.vehicle-searchable').forEach(input => {
        console.log('Found input:', input.id);
        createVehicleSearchableSelect(input.id);
    });
}

// Делаем глобально доступным
window.VEHICLES = VEHICLES;
window.createVehicleSearchableSelect = createVehicleSearchableSelect;
window.initVehicleSearchableFields = initVehicleSearchableFields;
